### ISSUE TITLE
My Intro Page - Change this page to attractive look

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#40]

**Comment by Candy505** [comment]
@minhaj-313 Hey ! I would like make some changes to the web page. Kindly assign me this issue.

**Comment by minhaj-313** [comment]
yeah ok, you can start doing, 
first give star to this repository and follow me 
and start doing, Try Your Best,

**Comment by sumit-022** [comment]
Can i work on this?

**Comment by minhaj-313** [comment]
> Can i work on this?

Yes, you can.
first give star to this repository and follow me
and start doing, Try Your Best,

**Comment by Candy505** [comment]
@minhaj-313 Okay so I am done.
 ![Screenshot (295)](https://user-images.githubusercontent.com/87769883/193592495-77f8dede-4f15-4587-bf95-3b4d7f82abe4.png)
![Screenshot (294)](https://user-images.githubusercontent.com/87769883/193592445-76b86cde-105c-4c71-b690-a3bdf6b45f21.png)
I have made another css file for the intro page because it was getting too complex for me to work. If that's not an issue and you're okay with the css animation , background colors, I'll do a pull request.

**Comment by minhaj-313** [comment]
yes

> @minhaj-313 Okay so I am done. ![Screenshot (295)](https://user-images.githubusercontent.com/87769883/193592495-77f8dede-4f15-4587-bf95-3b4d7f82abe4.png) ![Screenshot (294)](https://user-images.githubusercontent.com/87769883/193592445-76b86cde-105c-4c71-b690-a3bdf6b45f21.png) I have made another css file for the intro page because it was getting too complex for me to work. If that's not an issue and you're okay with the css animation , background colors, I'll do a pull request.
