### ISSUE TITLE
Add Responsive Filter Portfolio Gallery in MY Portfolio

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#45]

**Comment by Aahil13** [comment]
Good day. I would love to be assigned this project. But please could a comment be made on it for clarity

**Comment by minhaj-313** [comment]
yes you can start doing @Aahil13 

you want to create new page as portfolio.html and start doing work on it, Create Responsive filter portfolio gallery.
Thanks for contributing.
please star to this repository and follow me before starting and do quality work and send screenshot then I will merge your PR with labeled as it hacktoberfest-updated.
Thank You

**Comment by Aahil13** [comment]
Alright @minhaj-313 I will do as you have requested.

**Comment by Aahil13** [comment]
@minhaj-313 I have followed you and starred the repository, but I have a question. 
Please what type of images do you need for the gallery

**Comment by minhaj-313** [comment]
> @minhaj-313 I have followed you and starred the repository, but I have a question. Please what type of images do you need for the gallery

Take any photo of computer or laptop it just for test after your PR I will add my own Projects.

**Comment by Aahil13** [comment]
Good day @minhaj-313.
I have completed the assigned task. I delayed it due to schoolwork, but it is finally ready.
I followed the design pattern of the main page and just created my page from that. Below is a screenshot of my work.
All buttons filter the gallery as requested.

![Screenshot (219)](https://user-images.githubusercontent.com/63567230/195486926-b4090c98-a736-455b-b6ff-5a4c3ed78a12.png)

**Comment by minhaj-313** [comment]
@Aahil13  Great Work. Thank You.
